# Generated by Django 5.0.2 on 2024-02-21 06:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Посетитель библиотеки',
                'verbose_name_plural': 'Посетители библиотеки',
            },
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Отдел библиотеки', 'verbose_name_plural': 'Отделы библиотеки'},
        ),
        migrations.CreateModel(
            name='HandedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handed_date', models.DateField(default=datetime.date.today, verbose_name='Дата взятия')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handed_books', to='core.book', verbose_name='Книга')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handed_books', to='core.client', verbose_name='Посетитель')),
            ],
            options={
                'verbose_name': 'Взятая на руки книга',
                'verbose_name_plural': 'Взятые на руки книги',
            },
        ),
    ]
